name: qianshi_music
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity_plus: 4.0.2
  logger: ^1.4.0
  crypto: 3.0.1
  shared_preferences: 2.2.2
  get: 4.6.6
  photo_view: 0.14.0
  lottie: ^1.1.0
  json_annotation: ^4.8.1
  pull_to_refresh: ^2.0.0
  image_cropper: ^5.0.0
  flutter_easyloading: ^3.0.5
  curved_navigation_bar: ^1.0.3
  dio: 5.3.3
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  permission_handler: ^9.2.0
  audio_session: ^0.1.6
  flutter_sound: ^9.2.13
  flutter_screenutil: ^5.9.0
  common_utils: ^2.1.0
  video_player: ^2.2.11
  auto_orientation: ^2.2.1
  brightness_volume: ^1.0.3
  animations: ^2.0.8
  image_picker: ^1.0.5
  flutter_staggered_animations: ^1.1.1
  card_swiper: ^3.0.1
  file_picker: ^6.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  json_serializable: 6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
